# Generated by Django 6.0.4 on 2026-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_artwork_price_alter_artwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KSH', 'KSH')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='artwork',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artwork',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
