# Generated by Django 6.0.4 on 2026-05-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='profile',
            name='receive_updates',
            field=models.BooleanField(default=True),
        ),
    ]
